language: cpp
matrix:
  include:

    #linux gcc-8
    dist: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-8
    env: 

    script:
      - CC=gcc-8 CXX=g++8 cmake .
      - cmake --build . -- -j2
      - ctest -j2