language: cpp
matrix:
  include:

    #linux gcc-8
    os: linux
    dist: xenial
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-8
          - g++-8


    script:
      #have to export these here instead of an env section as travis will overwrite them
      - export CC=gcc-8
      - export CXX=g++-8

      - cmake .
      - cmake --build . -- -j2
      - ctest -j2