language: cpp

#ignore the commits while I setup 
branches:
  except:
    -appveyor_setup

matrix:
  include:

    #linux gcc-8
#    - os: linux
#      dist: xenial 
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - gcc-8
#            - g++-8
#      compiler: gcc-8
#
#      script:
#        #have to export these here instead of an env section as travis will overwrite them
#        - export CC=gcc-8
#        - export CXX=g++-8
#
#        - cmake .
#        - cmake --build . -- -j2
#        - ctest -j2
# 
#    #linux clang-7
#    - os: linux
#      dist: xenial
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - libstdc++-8-dev
#      compiler: clang-7
#
#      script:
#        #technically not needed but nice for consistancy with the gcc ones
#        - export CC=clang
#        - export CXX=clang++
#
#        - cmake .
#        - cmake --build . -- -j2
#        - ctest -j2

    #osx clang
    - os: osx
      script:
        - cmake --version
        - cmake .
        - cmake --build . -- -j2
        - ctest -j2

    #linux gcc-7
#    - os: linux
#      dist: xenial 
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - gcc-7
#            - g++-7
#      compiler: gcc-7
#
#      script:
#        #have to export these here instead of an env section as travis will overwrite them
#        - export CC=gcc-7
#        - export CXX=g++-7
#  
#        - cmake .
#        - cmake --build . -- -j2
#        - ctest -j2