version: 0.0.b{build}
pull_requests:
  do_not_increment_build_number: true
image:
- Visual Studio 2017
- Visual Studio 2019 Preview
install:
- cmd: git submodule -q update --init
build_script:
- cmd: >-
    mkdir build

    cd build

    cmake ..

    cmake --build . --config "Debug"
test_script:
- cmd: ctest -C Debug